[build]
  command = "npm test && npm run sync:video-reels"
  publish = "gdebenz_ui/static"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/static/*"
  to = "/:splat"
  status = 200
